### ISSUE TITLE
Stackwalk error in Windows

### ISSUE THREAD

**Issue by robertohuertasm** [acrisci/simple-breakpad-server#11]
Unfortunately, there's an [error](https://github.com/electron/node-minidump/issues/26) in the `minidump` package that makes this not to work in Windows.

I've submitted a PR to [chromium-breakpad#26](https://github.com/electron/chromium-breakpad/pull/6) so it can be fixed soon

**Comment by acrisci** [comment]
Thanks. Let me know if there's anything I can do to fix it.

**Comment by borlam** [comment]
Hi all,
I am reporting the crash of my electron app properly, and then upload symfiles for electron and other library, but I am obtaining an error. Looks that the symfiles is not associated to the minidump properly.
<img width="282" alt="Captura" src="https://user-images.githubusercontent.com/9450299/69135828-0b6b5600-0aba-11ea-8531-29fe6b5183b3.PNG">

**Comment by Jimbly** [comment]
I've merged @robertohuertasm's PR into @jimbly/minidump so there is at least a workaround for now.  Seems like breakpad has maybe just dropped Windows as a supported target (or, perhaps you have to build with make/g++, as at least can no longer use node-gyp/MSVC anymore automatically in a Node.js project), so I've just manually included the last working Win32 exe as part of the package.
