### ISSUE TITLE
Use minidump_stackwalk.exe to parse dump under windows system, unable to locate the specific code location, and do not display stack information

### ISSUE THREAD

**Issue by WABWH** [acrisci/simple-breakpad-server#26]
i am try to use   
 minidump_stackwalk.exe  XX.dmp A.sym

to parse dump file, but  unable to locate the specific code location, and do not display stack information;

could you tell me how to use minidump_stackwalk to locate the specific code location or isplay stack information;

**Comment by WABWH** [comment]
and  i use the same order under linux system is ok

**Comment by Jimbly** [comment]
Does this issue have anything to do with the `simple-breakpad-server`?  This server uses the `minidump` module to generate stack traces, and I believe it works fine on Windows (though I have not tried in a very long time, so it's possible some dependencies have rotted).

**Comment by WABWH** [comment]
> Does this issue have anything to do with the `simple-breakpad-server`? This server uses the `minidump` module to generate stack traces, and I believe it works fine on Windows (though I have not tried in a very long time, so it's possible some dependencies have rotted).
